[package]
name = "geoip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maxminddb = "=0.23.0"
hyper = { version = "=0.14.20", features = ["full"] }
tokio = { version = "=1.20.0", features = ["full"] }
futures = { version = "=0.3" }
futures-util = { version = "=0.3.21" }